[tests.php]

framework = "PestPHP"

use_mocks = false

num_desired_tests = 2

plan_instructions = """
1. Unless otherwise specified all PHP applications are built on Laravel.
2. Tests should always be written using PestPHP not PHPUnit.
"""

example_test = """
it('checks if true equals true', function() {
  expect(true)->toBeTrue();
});
"""
